name: mascarade
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  font_awesome_flutter: ^10.3.0
  pocketbase: ^0.6.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0


flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/vampire_background_by_cybergothpunkfreak_d1honom.jpg"
  color_dark: "#434343"
  image_dark: "assets/images/vampire_background_by_cybergothpunkfreak_d1honom.jpg"
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/vampire_background_by_cybergothpunkfreak_cropped.jpg"

flutter:
  uses-material-design: true
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  assets:
    - assets/images/
  fonts:
    - family: Cardo
      fonts:
        - asset: assets/fonts/Cardo/Cardo-Regular.ttf
        - asset: assets/fonts/Cardo/Cardo-Italic.ttf
          style: italic
        - asset: assets/fonts/Cardo/Cardo-Bold.ttf
          weight: 700
